export const recipe_list = [
  {
    id: "1",
    title: "Chocolate Protein Oats",
    img_url: "https://i.ibb.co/FBP3QZ8/breakfast3.jpg",
    subtitle: "Energy Booster",
    desc: "Dive into the creamy delight of Chocolate Protein Overnight Oats. Whole grain oats merge with rich chocolate and a protein boost, creating a decadent yet nutritious start to your day. Sweetened naturally and finished with a hint of sea salt, it's a quick, satisfying fix for your morning cravings.",
    mealType: "Breakfast",
  },
  {
    id: "2",
    title: "Acai Bowl",
    img_url: "https://i.ibb.co/jWRTjgS/breakfast2.jpg",
    subtitle: "Bliss in a Bowl",
    desc: "Dive into a refreshing Berry Acai Bowl, where the exotic acai berry meets a colorful array of fresh berries. Topped with crunchy granola and a drizzle of honey, this bowl is a perfect harmony of tart, sweet, and crunchy, making it an irresistible, energizing treat.",
    mealType: "Breakfast",
  },
  {
    id: "3",
    title: "Berry Nut Oatmeal Delight",
    img_url: "https://i.ibb.co/B4vDszf/breakfast1.jpg",
    subtitle: "A Symphony of Wholesome Goodness",
    desc: "Start your day with our Berry Nut Oatmeal Delight, where creamy, slow-cooked oats meet the juicy burst of fresh berries and the earthy crunch of toasted nuts. This heartwarming bowl is a testament to simplicity and nutrition, offering a balanced blend of flavors and textures that nourish the soul and energize the body.",
    mealType: "Breakfast",
  },
  {
    id: "4",
    title: "Buddha Bowl",
    img_url: "https://i.ibb.co/1zjdxB0/buddha-Bowl.jpg",
    subtitle: "Delicious and Nutritious",
    desc: "Discover the perfect balance of flavors and nutrients in our Buddha Bowl. Packed with protein, fiber, and essential vitamins.",
    mealType: "Lunch",
  },
  {
    id: "5",
    title: "Mediterranean Salad",
    img_url: "https://i.ibb.co/Ps2XDmd/food-Image2.jpg",
    subtitle: "Fresh and Flavorful",
    desc: "Indulge in the vibrant tastes of the Mediterranean with our refreshing salad. Bursting with fresh veggies, olives, feta cheese, and a tangy vinaigrette.",
    mealType: "Lunch",
  },
  {
    id: "6",
    title: "Veggie Flat Wrap",
    img_url: "https://i.ibb.co/DpqBwpZ/veggie-Wrap.jpg",
    subtitle: "Full of Fiber",
    desc: "Savor the freshness in every bite with our Veggie Wrap, a vibrant medley of crisp vegetables and tangy sauce, all snugly wrapped in a soft, whole-grain tortilla. Perfect for a quick, healthy lunch on the go!",
    mealType: "Lunch",
  },
];
